### PR TITLE
Add new eShop Tracks

### PR DESCRIPTION
**Pull request by IAmTheNerdNextDoor**
Added some new eShop tracks. A loading loop (doesn't loop perfectly but it's more to do with how the song restarts and not the file itself.), the loading jingle with the finish bit at the end, and the unused dummy beta track.

Tested it on my side and it works okay.

Unrelated, I found a bug but not really a big one. Switch from a shopping tab while it's playing music to a settings tab and it will continue to play shopping music until you switch tabs to a non settings or shopping site, wait for it to stop, and then switch back then it plays settings music.

Let me know what you think!

### CODE REVIEW

**Comment by WebSnke** [comment]
Why is the dummy track the Mario Kart: Double Dash theme?

**Comment by AFellowSpeedrunner** [comment]
Huh, I didn't actually know that. I just knew the eShop had a dummy track and that was the track. I knew it sounded quite like a Mario Kart track but I didn't know. I added it though because it was used in the eShop. If you want me to, I can remove it.

**Comment by WebSnke** [comment]
Sorry, but I don't think that adding these songs would improve the project...
I suggest that you always create an issue first about an idea you have for the project.

Thank you anyway and feel free to contribute to this project in the future.

**Comment by AFellowSpeedrunner** [comment]
Alright, I see. Thanks anyways.

**Pull request closed without merging**
