### PR TITLE
Added the NNID Account Settings music.

### PR DESCRIPTION
**Pull request by AFellowSpeedrunner**
Thought it would be a valuable addition.

Thanks for making this extension! :D

### CODE REVIEW

**Review by WebSnke — CHANGES_REQUESTED** [review]
Thanks for your pull request. However, the string that you added to settings.html is overflowing. Could you remove the max-width in settings.css to resolve that issue?

**Comment by AFellowSpeedrunner** [comment]
Sure, just give me a second.

**Comment by AFellowSpeedrunner** [comment]
Alright, fixed it. Let me know what you think.

**Review by WebSnke — APPROVED** [review]
LGTM!

**Comment by AFellowSpeedrunner** [comment]
Thanks for merging my changes in!

**Comment by WebSnke** [comment]
> Thanks for merging my changes in!

Feel free to submit more pull reqeusts in the future.

**Pull request merged**
